### ISSUE TITLE
Where laravel version 

### ISSUE THREAD

**Issue by muhammadcahya** [uilibrary/arctic-admin#2]
Hello, first, I want to say that I am impressed with your theme, I apologize too if possible in the future I have many requests 

Before starting anything, I wanted to ask because the source I got didn't have the laravel version. While the title and demo write "Arctic - HTML, VueJs, Angular, React & Laravel Admin Dashboard Template"

Note : I bought it on themeforest, to ask for an envato license or anything please private message

**Comment by naime-hossain** [comment]
Provide your Envato invoice and Gmail here uilib.help@gmail.com we will give access to the laravel file.
 forget to add the laravel version on ThemeForest files, we will add in the next update.
you can add your query here and don't forget to rate our item on ThemeForest if you like it. :) 
Thanks

**Comment by muhammadcahya** [comment]
Solve on current update
